### ISSUE TITLE
Following a torrent for comment updates bugs out and it instead follows it as torrent updates

### ISSUE THREAD

**Issue by ArjixWasTaken** [ArjixGamer/Nyaa-Utility#4]
known bug that i dont fucking know how it happens in the first place

**Comment by ArjixWasTaken** [comment]
I think that got fixed, so I'll close this for now.

**Comment by motbob** [comment]
Was this fixed in 1.6? Following torrents is still unreliable in Firefox.

**Comment by ArjixWasTaken** [comment]
> Was this fixed in 1.6? Following torrents is still unreliable in Firefox.

Yep, it was fixed in this [commit](https://github.com/ArjixWasTaken/Nyaa-Utility/commit/4a1af05b9cef4616ba7f866d20d62276eddc1c7b).

I'm pretty sure that's in 1.5 ver
Have you tried resetting the data from the extension settings?

**Comment by ArjixWasTaken** [comment]
Reopened in case this is still a thing.

**Comment by ArjixWasTaken** [comment]
I guess I should push 1.6 to firefox/chrome.
It's semi-done.

**Comment by ArjixWasTaken** [comment]
> > Was this fixed in 1.6? Following torrents is still unreliable in Firefox.
> 
> Yep, it was fixed in this [commit](https://github.com/ArjixWasTaken/Nyaa-Utility/commit/4a1af05b9cef4616ba7f866d20d62276eddc1c7b).
> 
> I'm pretty sure that's in 1.5 ver
> Have you tried resetting the data from the extension settings?

My honest guess is that the two tasks shared the same variable references (because chrome is like, running them all in the same scope), so if they ran at the same time unexpected results would happen.
The fix was to rename the variable references and also correctly format some integers.

**Comment by motbob** [comment]
I'll do more testing and report back later but I just installed the add-on this week so I don't think it's fixed in 1.5.

**Comment by motbob** [comment]
I will make a new issue. I don't think my problem is related to this one.

**Comment by ArjixWasTaken** [comment]
closing this as it was not actually the problem
